
import localFont from "next/font/local";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft, faChartLine, faChartSimple, faFileLines, faRightFromBracket } from "@fortawesome/free-solid-svg-icons";
import LogoutButton from "@/components/buttons/LogoutButton";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children, ...rest }) {
    const headersList = headers();
    console.log(headersList.get('next-url'))
    const session = await getServerSession(authOptions)

    if(!session) {
        return redirect('/');
    } 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
      <main className="flex min-h-screen ">
        
         <aside className="bg-white w-48 shadow p-4">
          
         <div className ="flex flex-col gap-4 items-center">
           <div className='rounded-full flex-col  overflow-hidden aspect-square w-24 mx-auto '>
                    <Image src={session.user.image} width={256} height={256} alt={'avatar'} />
                   
                </div>
                
                <h1 className="text-center text-2xl font-bold text-gray-900">{session.user.name}</h1>
                </div>
           <div className="text-center">
         <AppSidebar />
           </div>
        
         </aside>
          <div className="grow">
            <div className="bg-white m-8 p-4 shadow ">
            {children}
            </div>
          
          </div>
          
        </main>
        
      </body>
    </html>
  );
}
