import localFont from "next/font/local";
import "../../globals.css";
import Header from "@/components/Header";



export const metadata = {
  title: "Droppp.link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <main>

          {children}
          
        </main>
        
      </body>
    </html>
  );
}
